project:
  type: website
  output-dir: docs
website:
  title: "Bo Wen's Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - href: project.qmd
        text: Project
      # - text: More
      #   menu:
      #     - href: projects.qmd
      #       text: Projects
      #     - text: Blog
      #       href: blog.qmd

format:
  html:
    theme:
      light: Lumen #Morph #Pulse #Sandstone #Sketchy #Solar #Superhero #vapor
      dark: [Lumen, theme-dark.scss]
    css: styles.css
    toc: true
    
languages:
  r:
    path: C:/Program Files/R/R-4.2.3/bin/Rscript.exe
  python:
    path: C:/Users/wenbo/anaconda3/python.exe
